//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int id { get; set; }
        public string license { get; set; }
        public string cardId { get; set; }
        public Nullable<System.DateTime> checkInTime { get; set; }
        public Nullable<System.DateTime> checkOutTime { get; set; }
        public Nullable<int> pricesId { get; set; }
        public string checkInUserName { get; set; }
        public string checkOutUserName { get; set; }
    
        public virtual Price Price { get; set; }
    }
}
