//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Spellduty_User = new HashSet<Spellduty_User>();
        }
    
        public int users_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> born { get; set; }
        public string user_address { get; set; }
        public string phone { get; set; }
        public string acc { get; set; }
        public Nullable<int> user_role { get; set; }
        public string pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spellduty_User> Spellduty_User { get; set; }
    }
}
